/**
 * The inline deep tier's manifest: the same compressed, still-exact
 * pin `tests/conformance/registry-sweep-clusters.ts` defines, keyed by
 * the inline coordinate instead of the line one.
 *
 * The FORMAT is shared, deliberately - `factsOfBuckets` there records
 * the count, the first five ids and the sha256 of the full sorted id
 * list, and `loadSweepClusters` validates a manifest at any path - so
 * the two deep manifests cannot drift on what a cluster records or on
 * how strictly it is read. What is not shared is the KEY, because the
 * two sweeps triage on different axes: a line-registry decision is
 * made about a grid and a byte operator, an inline one about the
 * CONSTRUCT KINDS a row spells and the axis that placed them. The
 * byte operator is left out of the inline key on measurement, not on
 * principle - the classes span all nine of them uniformly, so keying
 * on it spells 24 findings 169 times, and a class that did belong to
 * one operator alone would still move a count and a digest.
 *
 * The key needs no parsing here at all. Every row already carries its
 * own cluster (`InlineSweepRow.cluster`, written by the registry that
 * knew the kind and the axis while it built the shape), so this
 * module buckets by a field rather than by a substring of an id.
 *
 * A LIBRARY module: `scripts/inline-sweep-triage.ts` writes the
 * manifest and `inline-sweep.deep.test.ts` gates against it.
 */

import {
  factsOfBuckets,
  type ClusterFacts,
} from "./registry-sweep-clusters.js";
import type { SweepFailure } from "./registry-sweep.js";
import type { InlineSweepRow } from "./inline-sweep.js";

/** Repo-relative manifest path for the inline deep tier. */
export const INLINE_SWEEP_DEEP_MANIFEST_PATH =
  "tests/conformance/inline-sweep-deep-manifest.json";

/**
 * Where the inline deep gate dumps the full failing list when it does
 * not agree with the manifest. Under `reports/`, which is gitignored:
 * it is a triage aid regenerated by every failing run, not a record.
 */
export const INLINE_SWEEP_DEEP_DUMP_PATH =
  "reports/inline-sweep-deep-failures.json";

/**
 * Compresses a failing set into its clusters.
 *
 * Takes the ROWS as well as the failures, because the cluster
 * coordinate lives on the row: walking the rows and looking each one's
 * verdict up is total, where looking a failure's row up would have to
 * answer for an id that names no row.
 * @param rows - every row the sweep ran, in sweep order
 * @param failures - the failing ones, in any order
 * @returns the clusters, keyed and ordered by cluster key
 */
export function inlineClusterFacts(
  rows: readonly InlineSweepRow[],
  failures: readonly SweepFailure[],
): Map<string, ClusterFacts> {
  const verdicts = new Map(
    failures.map((failure) => [failure.id, failure.fails]),
  );
  const ids = new Map<string, string[]>();
  for (const row of rows) {
    const fails = verdicts.get(row.id);
    if (fails === undefined) {
      continue;
    }
    const key = `${row.cluster}/${fails.join("+")}`;
    const bucket = ids.get(key) ?? [];
    bucket.push(row.id);
    ids.set(key, bucket);
  }
  return factsOfBuckets(ids);
}
