/**
 * Where the inline deep tier's cluster manifest and its triage dump
 * live.
 *
 * The manifest's FORMAT and its clustering are shared with the line
 * registry's - `factsOfBuckets` in
 * `tests/conformance/registry-sweep-clusters.ts` records the count,
 * the first five ids and the sha256 of the full sorted id list,
 * `clusterFactsOfRows` there keys a cluster off the class each row
 * carries, and `loadSweepClusters` validates a manifest at any path -
 * so no two sweeps can drift on what a cluster records or on how
 * strictly it is read. What is not shared is the KEY, and that is the
 * registry's own decision, written at `InlineShape.cluster`: a
 * line-registry cluster is a grid and a byte operator, an inline one
 * is the CONSTRUCT KINDS a row spells and the axis that placed them.
 * Why the operator is left out of the inline key, on measurement
 * rather than on principle, is written at `InlineSweepRow.cluster`.
 *
 * Two paths and no logic, deliberately. They are here rather than
 * beside the row sets because a path is what a triage runner and a
 * gate have to agree on, and the two of them import nothing else from
 * each other.
 */

/** Repo-relative manifest path for the inline deep tier. */
export const INLINE_SWEEP_DEEP_MANIFEST_PATH =
  "tests/conformance/inline-sweep-deep-manifest.json";

/**
 * Where the inline deep gate dumps the full failing list when it does
 * not agree with the manifest. Under `reports/`, which is gitignored:
 * it is a triage aid regenerated by every failing run, not a record.
 */
export const INLINE_SWEEP_DEEP_DUMP_PATH =
  "reports/inline-sweep-deep-failures.json";
