/**
 * The reflow-line sweep: list items whose body is a product over the
 * two LINE KINDS that decide whether a line break survives a reflow,
 * run through the same three differential properties
 * `tests/conformance/registry-sweep.ts` runs on the line registry's
 * grids.
 *
 * WHAT IT REACHES THAT NOTHING ELSE DOES. The line registry
 * (`deepTierRows`), the inline registry (`inlineDeepTierRows`) and the
 * list-shape sweep (`sweepDocuments`) spell no document carrying
 * either class's OWN line kind, a hard-break line or a construct
 * broken across two source lines. They do share documents with this
 * table, a minority of the rows on the plain marker line, and every
 * one of those carries neither line kind: the overlap is what the
 * alphabets' four common symbols make, not a coordinate this sweep
 * exists for. Structural rather than incidental: the list-shape
 * alphabet carries no hard-break line and no symbol that occupies two
 * source lines, so its product contains no document in which a ` +`
 * decides whether a line break survives and none in which a construct
 * opens on one indented line and closes on the next, and no
 * enumeration but this one spells a checklist marker at all. The
 * inline registry does vary the text inside a run, but it wraps ONE
 * run in ONE context line, so a document of its is a document of a
 * different shape entirely: no row of it is a member of either class
 * here. Those are the lines the printer's reflow decisions are made
 * about, which is why an absolute pin over them is worth its wall
 * time.
 *
 * THE POPULATION IS A DECLARED TABLE, not a filter over anyone else's
 * enumeration. Each class names its own alphabet and its own
 * witnesses, and what it spells is a function of that table alone, so
 * a change to another generator cannot silently move what this one
 * sweeps. The cost is that the hard-break alphabet restates the eleven
 * list-shape symbols rather than importing them; the benefit is that
 * the pinned population counts are counts OF this table, which is what
 * makes them checkable.
 *
 * Each class is the depth-1-to-3 product over its alphabet under two
 * prefixes per marker line: a one-line item, and the same item with a
 * second text line, which is the shorter of the two shapes reflow can
 * move. The second prefix is the first plus the alphabet's FIRST
 * symbol, so the two products overlap by construction and the
 * deduplication is a property of the definition rather than an
 * accident of the strings. The marker lines are {@link ITEM_LINES},
 * the plain item and the three checklist heads.
 *
 * ONE ROW PER DOCUMENT. The two alphabets share four symbols, so both
 * classes spell some of the same documents; the first class in the
 * table that spells one mints it and the second does not, on the rule
 * `crossByteOperators` follows in `generated-sweep.ts` - the same
 * bytes are never assessed twice under two names. The class that
 * minted a row is the row's cluster, so a document's cluster is a
 * function of the table's order, and the per-class row counts pinned
 * in `reflow-line-sweep.test.ts` are what hold that order still.
 *
 * NO ROW IS RENDER-BLIND. Every document is a list item that renders,
 * so the fidelity comparison is never vacuous the way it is for a
 * comment block in the line registry.
 *
 * ONE TIER, in `bun run test`. The whole population runs inside the
 * suite's existing critical path, which the list-shape sweep sets and
 * this file does not reach, so there is nothing here to split. No
 * figure is quoted: every reading of it moves with the machine and the
 * load, and vitest prints the file's own duration on every run.
 *
 * Failures are held by `reflow-line-sweep-manifest.json` as CLUSTERS,
 * on the exact-agreement terms every sweep manifest uses: a cluster
 * records its row count, its first five ids and the sha256 of its full
 * sorted id list, and the gate recomputes all three, so a row that
 * appears, vanishes or moves between clusters turns the suite red.
 *
 * A LIBRARY module: the row set and the manifest paths, with the gate
 * that consumes them living in its own test file.
 */

import type { SweepRow } from "./registry-sweep.js";

/** One generated document, carrying the class that minted it. */
export interface ReflowLineRow extends SweepRow {
  /**
   * The class that minted this document: the first half of its
   * cluster key, with the failed properties appended by the gate.
   */
  readonly cluster: string;
}

/** Repo-relative manifest path for this sweep's known failures. */
export const REFLOW_LINE_SWEEP_MANIFEST_PATH =
  "tests/conformance/reflow-line-sweep-manifest.json";

/**
 * Where the gate dumps the full failing list when it does not agree
 * with the manifest. Under `reports/`, which is gitignored: it is a
 * triage aid regenerated by every failing run, not a record.
 */
export const REFLOW_LINE_SWEEP_DUMP_PATH =
  "reports/reflow-line-sweep-failures.json";

/** How many symbols the longest body of a class's product spells. */
const DEPTH = 3;

/**
 * The marker lines the products open with: the item's own first line,
 * varied over the CHECKLIST HEAD.
 *
 * Asciidoctor reads a checkbox off an unordered item's first line and
 * off nothing else (`item_text.start_with?('[ ] ', '[x] ', '[*] ')`,
 * parser.rb l.1330, whose arm slices those four characters off the
 * item's text), so a checklist item's TEXT starts four columns past
 * where a plain item's does while the marker line still spells one
 * item. That offset is the one the printer replays a block from
 * (`replayLines`, src/print/reflow.ts, reached from src/print/list.ts),
 * which makes the head a reflow coordinate rather than a decoration:
 * the item's text moving four columns changes which bytes a replayed
 * line opens at, and every line kind in the alphabets below asks its
 * own question of that block.
 *
 * All three spellings, because the reader distinguishes all three and
 * the printer does not: `[x]` and `[*]` are one state to Asciidoctor
 * and `[x]` is the only way back (`formatCheckbox`, src/print/list.ts),
 * so `[*]` is the one head whose output bytes differ from its input's,
 * and its `*` is a bold delimiter as well.
 *
 * The tab and form-feed heads (`* [x]<TAB>a`) are NOT here, and both
 * exclusions were measured over this table rather than judged. Neither
 * is a checkbox to either program, since the prefix's fourth character
 * is a literal space. A head added here spells a whole marker line's
 * share of the table, which the row counts pinned in
 * `reflow-line-sweep.test.ts` measure; the tab head changed no row's
 * verdict anywhere in it, as the tree stands or with the checklist
 * replay offset reverted, and what it would pin is pinned by the rows
 * in tests/format/checklist.test.ts. The form-feed head fails fidelity
 * on all but a couple of dozen of the documents it would add, every
 * one of them the erasure that same file characterizes (the
 * marker-line guard puts `[x]` alone on its line, the fold joins with
 * a space, and the control byte is gone), on a byte no editor writes
 * into a text file.
 */
const ITEM_LINES = ["* a", "* [ ] a", "* [x] a", "* [*] a"] as const;

/**
 * The plain-text line that leads every alphabet here, which makes it
 * the line the second prefix adds: an item whose text is two lines,
 * the smallest shape whose reflow can join or refuse to join anything.
 */
const ITEM_TEXT = "para";

/** A hard-break line, the line no other enumeration's alphabet has. */
const HARD_BREAK = " +";

/** A line comment, which the reference drops from an item's text. */
const COMMENT = "// c";

/** A blank line, which ends an item's principal text. */
const BLANK = "";

/**
 * The list-shape sweep's own eleven symbols, restated rather than
 * imported. See the header: the pinned population counts are counts of
 * this table, and importing would let another module move what this
 * one spells without moving anything a reader of this file can see.
 */
const LINE_SHAPES = [
  ITEM_TEXT,
  "* a",
  "** b",
  "+",
  BLANK,
  "  lit",
  "  ** z",
  COMMENT,
  "[role]",
  "[[anc]]",
  ".T",
] as const;

/**
 * Constructs whose interior spans two source lines with BOTH lines
 * indented: the combination where the two directions of error meet. A
 * reader that takes the continuation for a column-0 line cancels a
 * block's indent strip, and one that takes an unindented continuation
 * for an indented line applies a strip the source did not ask for.
 */
const INDENTED_TWO_LINE_CONSTRUCTS = [
  "  *b\n  c* d",
  "  `b\n  c` d",
  "  https://e.com[b\n  c] d",
  "  mailto:a@b.c[b\n  c] d",
  "  +++b\n  c+++ d",
  "  #b\n  c# d",
] as const;

/**
 * Documents whose exact spelling is the point, carried beside the
 * product that cannot spell them.
 *
 * Each is a shape whose reading depends on a line no alphabet here
 * contains: an escaped mark, an attribute or character reference, a
 * construct nested inside another across a line break, an item whose
 * marker line already carries text, a construct broken across two
 * lines only one of which is indented.
 */
const INDENTED_TWO_LINE_WITNESSES = [
  // A line an inline construct opens, above a hard break, with an
  // indented line under it: the indent question asked of a line whose
  // leading bytes belong to a construct rather than to text.
  "* a\n*b* tail\n +\n  lit\n",
  // The same question with nothing but an indented line to ask it of.
  "* a\n  lit\n +\n",
  // A marker line that already carries text, so the item's first
  // source line is not the marker's own share alone.
  "* a see\nmailto:a@b.c[a] [x]\n +\n",
  // An ESCAPED mark: two lines that look like a span and are not.
  "* a\n  \\*b*\nc d\n +\n",
  // An attribute reference, which the reader resolves and the source
  // spells in bytes of its own.
  "* a\n  {attr} b\nc d\n +\n",
  // A character reference, likewise.
  "* a\n  &amp; b\nc d\n +\n",
  // A hard break INSIDE a span that closes on the next line.
  "* a\n  *b +\nc* d\n +\n",
  // A span nested inside a span, the pair broken across two lines.
  "* a\n  *b `q\nr` s* d\n +\n",
  // A two-line passthrough, both lines indented, above a comment and
  // a hard break: the comment is not in the text block at all, so the
  // indent question must skip it.
  "* a\n  +++b\n  c+++ d\n// c\n +\n",
  // The same shape with a link macro, whose interior holds the break.
  "* a\n  https://e.com[b\n  c] d\n// c\n +\n",
  // And both of those without the comment line, where the hard break
  // stands directly under the construct's closing line.
  "* a\n  https://e.com[b\n  c] d\n +\n",
  "* a\n  mailto:a@b.c[b\n  c] d\n +\n",
  // A line an inline construct opens, directly above a run of block
  // metadata. No alphabet here can spell the pair, and the rule that
  // decides whether a metadata run needs a break is asked of exactly
  // this neighbourhood.
  "* a\n*b* tail\n[role]\npara\n** b\n",
  "* a\nhttps://e.com[x] tail\n[[anc]]\npara\n +\n",
  // Two-line constructs whose lines are NOT both indented, for the
  // two kinds the both-indented alphabet is the only one to carry: a
  // mail macro broken at column 0, and a highlight span whose
  // continuation alone is indented.
  "* a\nmailto:a@b.c[b\nc] d\n +\n",
  "* a\n#b\n  c# d\n +\n",
] as const;

/**
 * The hard-break class's own witness: a checklist marker line whose
 * text is the break itself, over a plus one column further out.
 *
 * No marker line in {@link ITEM_LINES} spells it. The head there is
 * followed by text; here the four characters are the whole of what
 * precedes the break, so the question of where the item's text starts
 * is asked of a marker line that carries none. Both programs read a
 * checklist item on it. We record no checkbox, because the trailing
 * ` +` is taken as a break token before the prefix is tested (#316),
 * and the three properties here still pass, so the document mints no
 * cluster; what carrying it holds is that the shape is swept at all.
 */
const HARD_BREAK_WITNESSES = ["* [ ] +\n   +\n  z\n"] as const;

/** One declared class: an alphabet, and what rides beside its product. */
interface ReflowLineClass {
  /** The class name, which is the first half of its cluster key. */
  readonly name: "hard-break" | "indented-two-line";
  /**
   * The alphabet. The FIRST symbol is the line the second prefix
   * adds, which is what makes the two prefixes' products overlap.
   */
  readonly symbols: readonly [string, ...string[]];
  /** Documents carried beside the product, deduplicated into it. */
  readonly witnesses: readonly string[];
}

/** The two classes, in the order that decides which one mints a row. */
const CLASSES: readonly [ReflowLineClass, ...ReflowLineClass[]] = [
  {
    name: "hard-break",
    symbols: [...LINE_SHAPES, HARD_BREAK],
    witnesses: HARD_BREAK_WITNESSES,
  },
  {
    name: "indented-two-line",
    symbols: [
      ITEM_TEXT,
      BLANK,
      COMMENT,
      HARD_BREAK,
      ...INDENTED_TWO_LINE_CONSTRUCTS,
    ],
    witnesses: INDENTED_TWO_LINE_WITNESSES,
  },
];

/**
 * Every document one class spells: the exhaustive product under every
 * marker line's two prefixes, then its witnesses, deduplicated.
 * @param declared - the class to spell
 * @returns the distinct documents, product first, in generation order
 */
function classDocuments(declared: ReflowLineClass): string[] {
  const documents: string[] = [];
  const [continuation] = declared.symbols;
  const prefixes = ITEM_LINES.flatMap((item) => [
    `${item}\n`,
    `${item}\n${continuation}\n`,
  ]);
  for (const prefix of prefixes) {
    const grow = (lines: readonly string[], remaining: number): void => {
      for (const symbol of declared.symbols) {
        const next = [...lines, symbol];
        documents.push(`${prefix}${next.join("\n")}\n`);
        if (remaining > 1) {
          grow(next, remaining - 1);
        }
      }
    };
    grow([], DEPTH);
  }
  return [...new Set([...documents, ...declared.witnesses])];
}

/**
 * The document itself as a row id, escaped onto one line.
 *
 * The id has to BE the document: an index into a generated product
 * moves the moment an alphabet does, which would let a manifest
 * example silently name a different document than the one it was
 * written for. It has to be one line as well, because a cluster's
 * digest is taken over its ids joined by newlines, and an id carrying
 * a newline would make two different id lists digest the same. A JSON
 * string body is both, and it is what a reader can paste straight into
 * a test.
 * @param document_ - the generated document
 * @returns the document with its newlines and backslashes escaped
 */
function rowId(document_: string): string {
  return JSON.stringify(document_).slice(1, -1);
}

/**
 * The whole population: both classes' documents, each minted once by
 * the first class in the table that spells it.
 * @returns the rows, in class order and then in generation order
 */
export function reflowLineRows(): ReflowLineRow[] {
  const minted = new Set<string>();
  const rows: ReflowLineRow[] = [];
  for (const declared of CLASSES) {
    for (const document_ of classDocuments(declared)) {
      if (minted.has(document_)) {
        continue;
      }
      minted.add(document_);
      rows.push({
        id: rowId(document_),
        input: document_,
        renderBlind: false,
        cluster: declared.name,
      });
    }
  }
  return rows;
}
