/**
 * The deep tier's manifest format: the same exact-agreement pin the
 * per-row manifests use, compressed so a human can read it.
 *
 * WHY IT IS NOT A ROW LIST. The deep tier's failing set is five
 * figures wide. Written a row at a time it would be a JSON file
 * nobody reviews and every triage run rewrites wholesale, so the
 * diff that is supposed to say "this fix retired 400 coordinates"
 * says nothing a reader can check. Written as CLUSTERS it stays a
 * page: one line per failure class, with the count beside it.
 *
 * It is still EXACT. A cluster records three facts about the rows it
 * covers - how many there are, the first five ids in sorted order,
 * and the sha256 of the whole sorted id list - and the gate
 * recomputes all three. A row that appears, vanishes, or moves
 * between clusters changes a hash, so the manifest cannot absorb a
 * new failure by luck the way a bare count could. What it gives up
 * is only legibility of the individual row: which coordinate moved
 * has to come from the dump the gate writes, not from the diff.
 *
 * The cluster key is the failure's own coordinates: which grid the
 * row came from, which byte operator (if any) perturbed it, and the
 * properties it failed. Those are the axes a triage decision is
 * actually made on - "every crlf-perturbed pair row fails
 * idempotency" is one gap, not four thousand - and they are readable
 * straight off the row id, so clustering needs no state the sweep
 * does not already carry.
 *
 * A LIBRARY module: `scripts/registry-sweep-triage.ts` writes the
 * manifest and `registry-sweep.deep.test.ts` gates against it.
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import type { ConformanceProperty } from "./properties.js";
import type { SweepFailure } from "./registry-sweep.js";

/** Repo-relative manifest path for the deep tier's known failures. */
export const SWEEP_DEEP_MANIFEST_PATH =
  "tests/conformance/registry-sweep-deep-manifest.json";

/**
 * Where the deep gate dumps the full failing list when it does not
 * agree with the manifest. Under `reports/`, which is gitignored: it
 * is a triage aid regenerated by every failing run, not a record.
 */
export const SWEEP_DEEP_DUMP_PATH = "reports/registry-sweep-deep-failures.json";

/** The three recomputed facts about one failure cluster. */
export interface ClusterFacts {
  /** How many rows the cluster covers. */
  count: number;
  /** The first five row ids in sorted order, for reading by eye. */
  examples: string[];
  /** Hex sha256 of the sorted row ids joined by newlines. */
  sha256: string;
}

/** A manifest cluster: the recomputed facts plus its triage tag. */
export interface ClusterEntry extends ClusterFacts {
  /**
   * Gap issue reference like `#10`, or `UNTRIAGED` for clusters the
   * triage script found but nobody has mapped yet.
   */
  issue: string;
}

/** How many ids a cluster lists by name. */
const EXAMPLE_LIMIT = 5;

/**
 * The grid a row id came from. Read off the id rather than carried
 * on the row: `pairGrid` is the only generator that prefixes its
 * coordinates, and the sweep concatenates the two grids into one
 * list, so the prefix is the only surviving witness of the split.
 * @param id - a sweep row id, with or without its operator suffix
 * @returns the grid name
 */
function gridOf(id: string): string {
  return id.startsWith("pair/") ? "pair" : "standing";
}

/**
 * The byte operator a row id carries, or `clean` for the unperturbed
 * row. The suffix is `@<operatorId>` and operator ids contain no
 * `@`, so the LAST `@` is the separator.
 * @param id - a sweep row id
 * @returns the operator id, or `clean`
 */
function operatorOf(id: string): string {
  const at = id.lastIndexOf("@");
  return at === -1 ? "clean" : id.slice(at + 1);
}

/**
 * The cluster one failure belongs to: `<grid>/<operator>/<fails>`.
 * None of the three parts can contain a `/`, so the key parses back
 * unambiguously even though nothing needs to parse it today.
 * @param failure - one failing row's verdict
 * @returns the cluster key
 */
function clusterKeyOf(failure: SweepFailure): string {
  return `${gridOf(failure.id)}/${operatorOf(failure.id)}/${failure.fails.join("+")}`;
}

/**
 * Compresses a failing set into its clusters.
 *
 * Keys come out in sorted order so the manifest's JSON is stable
 * under rewriting: a triage run that changes one cluster must show a
 * one-cluster diff.
 * @param failures - every failing row, in any order
 * @returns the clusters, keyed and ordered by cluster key
 */
export function clusterFacts(
  failures: readonly SweepFailure[],
): Map<string, ClusterFacts> {
  const ids = new Map<string, string[]>();
  for (const failure of failures) {
    const key = clusterKeyOf(failure);
    const bucket = ids.get(key) ?? [];
    bucket.push(failure.id);
    ids.set(key, bucket);
  }
  const byKey = [...ids.entries()].toSorted(([a], [b]) =>
    a < b ? -1 : Number(a > b),
  );
  return new Map(
    byKey.map(([key, bucket]) => {
      const sorted = bucket.toSorted();
      return [
        key,
        {
          count: sorted.length,
          examples: sorted.slice(0, EXAMPLE_LIMIT),
          sha256: createHash("sha256").update(sorted.join("\n")).digest("hex"),
        },
      ];
    }),
  );
}

/** A hex sha256 digest and nothing else. */
const DIGEST = /^[0-9a-f]{64}$/v;

/**
 * Is this a well-formed example list: a non-empty run of strings, no
 * longer than a cluster is allowed to name?
 * @param examples - the candidate value
 * @returns true when it is
 */
function areExamples(examples: unknown): boolean {
  return (
    Array.isArray(examples) &&
    examples.length > 0 &&
    examples.length <= EXAMPLE_LIMIT &&
    examples.every((example) => typeof example === "string")
  );
}

/**
 * Type guard for one manifest cluster. Strict, for the reason
 * `quarantine.ts` is strict: a malformed entry would silently excuse
 * whatever rows it claims to cover.
 * @param value - unknown value from JSON
 * @returns true when the value is a well-formed cluster entry
 */
function isClusterEntry(value: unknown): value is ClusterEntry {
  if (typeof value !== "object" || value === null) {
    return false;
  }
  const { count, examples, sha256, issue } = value as {
    count?: unknown;
    examples?: unknown;
    sha256?: unknown;
    issue?: unknown;
  };
  return (
    typeof count === "number" &&
    count > 0 &&
    areExamples(examples) &&
    typeof sha256 === "string" &&
    DIGEST.test(sha256) &&
    typeof issue === "string"
  );
}

/**
 * Reads and validates the deep tier's manifest.
 * @param manifestPath - manifest file to read; defaults to the deep
 *   tier's. Tests point it at scratch files to exercise validation.
 * @returns map from cluster key to its entry
 */
export function loadSweepClusters(
  manifestPath: string = SWEEP_DEEP_MANIFEST_PATH,
): Map<string, ClusterEntry> {
  const parsed: unknown = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error(`${manifestPath}: expected an object`);
  }
  const clusters = new Map<string, ClusterEntry>();
  for (const [key, value] of Object.entries(parsed)) {
    if (!isClusterEntry(value)) {
      throw new Error(`${manifestPath}: malformed cluster for ${key}`);
    }
    clusters.set(key, value);
  }
  return clusters;
}

/**
 * The manifest's clusters with their issue tags dropped, so a
 * recomputed `clusterFacts` map compares against it directly.
 * @param manifest - the loaded manifest
 * @returns the same keys carrying only the recomputed facts
 */
export function factsOf(
  manifest: ReadonlyMap<string, ClusterEntry>,
): Map<string, ClusterFacts> {
  const sorted = [...manifest.entries()].toSorted(([a], [b]) =>
    a < b ? -1 : Number(a > b),
  );
  return new Map(
    sorted.map(([key, entry]) => [
      key,
      { count: entry.count, examples: entry.examples, sha256: entry.sha256 },
    ]),
  );
}

/**
 * A failing set as the dump file records it: every row, sorted, with
 * the properties it failed. The gate writes this when it disagrees
 * with the manifest, because the manifest itself names only five ids
 * per cluster and triage needs the rest.
 * @param failures - every failing row
 * @returns the dump's JSON text, newline-terminated
 */
export function dumpText(failures: readonly SweepFailure[]): string {
  const rows: Record<string, ConformanceProperty[]> = {};
  for (const failure of failures.toSorted((a, b) =>
    a.id < b.id ? -1 : Number(a.id > b.id),
  )) {
    rows[failure.id] = failure.fails;
  }
  return `${JSON.stringify(rows, undefined, 2)}\n`;
}
