/**
 * The classification data `scripts/fact-inventory.ts` gates against:
 * every `src/ast.ts` property, sorted into FACTS (a printer under
 * `src/print/` reads it to choose an output SHAPE) or EXEMPT (a
 * discriminant, position bookkeeping, structural containment,
 * verbatim content, an unread record, a type-level sentinel, or a
 * container whose own arm's fields are classified separately). The
 * criterion, the verification method, and the surprises it turned up
 * are stated in `scripts/fact-inventory.ts`'s own module doc — this
 * file is the two maps alone, split out so that file stays under the
 * `max-lines` ceiling.
 *
 * Reasons are kept SHORT here on purpose (most owe their length to a
 * long key, not a long reason): the narrative for each recorded fact
 * — where the reparse-ledger fits, which test already exercises it —
 * lives in `scripts/fact-inventory-ledger.json`, which is what a
 * reader chasing "why is this a fact" should open next.
 */

/** Selects which printer function runs; carries no spelling of its own. */
const TYPE_DISCRIMINANT =
  "type discriminant, not a print-shape choice of its own";
/** The printer's byte output never reads this. */
const POSITION = "position bookkeeping, not read by the printer";
/** Walked by Prettier's path.map or the printer's own recursive print. */
const STRUCTURAL = "structural containment, not a shape choice of its own";
/** Copied into the output unconditionally; no branch on its own value. */
const CONTENT = "verbatim leaf content, copied unconditionally";
/** Constructed at parse time; no `src/print/*.ts` reference found. */
const UNREAD = "recorded but unread under src/print (verified by grep)";
/** `?: undefined`; never holds a runtime value. */
const SENTINEL = "type-level sentinel, never holds a value";
/** A record/union pointer whose own arms are classified separately. */
const CONTAINER = "container; its arm's fields are classified separately";

/**
 * Fields read under `src/print/` to choose between output shapes —
 * the recorded facts themselves. See `scripts/fact-inventory.ts` for
 * the criterion and `scripts/fact-inventory-ledger.json` for the
 * per-fact narrative.
 */
export const FACTS: ReadonlyMap<string, string> = new Map([
  ["DocumentNode.byteOrderMark", "printer.ts replays it"],
  ["ParagraphNode.firstWordEndsItsLine", "block-start-hazard.ts's question"],
  ["BoldNode.constrained", "mark width choice"],
  ["ItalicNode.constrained", "mark width choice"],
  ["MonospaceNode.constrained", "mark width choice"],
  ["HighlightNode.constrained", "mark width choice"],
  ["CurvedQuoteNode.quote", "entity-pair choice"],
  ["LinkNode.text", "3-state bracket spelling"],
  ["InlineAnchorNode.form", "bracket-width choice"],
  ["InlineAnchorNode.reftext", "verbatim-replay framing"],
  ["HeadingNode.level", "only record of marker count"],
  ["DocumentHeaderNode.underline", "compat-mode spelling"],
  ["DiscreteHeadingNode.level", "marker-count fact"],
  ["CommentNode.commentType", "// vs //// choice"],
  ["AttributeEntryNode.unset", "collapses two spellings"],
  ["ListNode.variant", "callout marker path choice"],
  ["ListNode.marker", "printedGap's gap-fold key"],
  ["LeafDelimitedBlockNode.variant", "delimiter char lookup"],
  ["LeafDelimitedBlockNode.form", "framing-strategy choice"],
  ["FencedCodeBlockNode.variant", "delimiter char lookup"],
  ["FencedCodeBlockNode.form", "framing-strategy choice"],
  ["MasqueradedBlockNode.variant", "style-attribute label"],
  ["MasqueradedBlockNode.form", "framing-strategy choice"],
  ["IndentedLiteralBlockNode.variant", "delimiter char lookup"],
  ["IndentedLiteralBlockNode.form", "framing-strategy choice"],
  ["ParagraphFormBlockNode.variant", "style-attribute label"],
  ["ParagraphFormBlockNode.form", "framing-strategy choice"],
  ["LeafDelimitedBlockNode.annotatedBy", "invariant (xi)"],
  ["FencedCodeBlockNode.annotatedBy", "invariant (xi)"],
  ["FencedCodeBlockNode.language", "[source,lang] emission"],
  ["MasqueradedBlockNode.annotatedBy", "invariant (xi)"],
  ["MasqueradedBlockNode.sourceDelimiter", "invariant (xiii)"],
  ["IndentedLiteralBlockNode.annotatedBy", "invariant (xi)"],
  ["ParagraphFormBlockNode.annotatedBy", "invariant (xi)"],
  ["OpenParentBlockNode.openDelimiter", "tilde spelling, issue #64"],
  ["CompoundParentBlockNode.variant", "only record of the delimiter"],
  ["AdmonitionNode.form", "label vs delimited-wrapper"],
  ["ItemBody.trailingContinuation", "issue #181's landed lemma"],
  ["ItemBody.detachedTail", "detachedTail print arm"],
  ["ItemBody.activeTail", "blank-line count after list"],
  ["ItemBody.everyTextLineIndented", "reflow-guard input"],
  ["ListItemNode.markerSpelling", "printed marker bytes"],
  ["ListItemNode.markerIndent", "structure, not decoration"],
  ["ListItemNode.checkbox", "checklist marker bytes"],
  ["ListItemNode.calloutNumber", "callout marker bytes"],
  ["ItemBlock.gap", "the brief's own gap example"],
  ["DescriptionTermNode.line", "keeps three spellings apart"],
  ["DescriptionListItemNode.printing", "own doc: never re-derived"],
  ["TermEntry.gap", "gap alphabet, for a term"],
  ["TableNode.open", "psv/csv/dsv family choice"],
  ["TableNode.columns", "gates ragged-row decline"],
  ["TableNode.leadingRuns", "gates interior-content check"],
  ["TableNode.annotatedBy", "not covered by invariant (xi)"],
  ["TableNode.attrlistUnread", "declines layout normalization"],
  ["TableClose#0.kind", "gates the closing line"],
  ["TableClose#1.kind", "same fact, other arm"],
  ["TableCutting.format", "table-layout.ts's isNotPsv"],
  ["TableCutting.separator", "table-layout.ts's isNotPsv"],
  ["TableColumnSpec.style", "suppresses ws normalization"],
  ["TableCellNode.columnIndex", "own doc: recorded, not derived"],
  ["TableCellOpening#0.kind", "separator vs lineStart choice"],
  ["TableCellOpening#1.kind", "same fact, other arms"],
  ["TableTextRun.kind", "content/comment/blank choice"],
  ["TableTextRun.image", "table-partition bytes, (xv)"],
  ["TableCellSpec.style", "opening.parsed.style read"],
  ["TableCellRepeat#0.kind", "none/span/duplicate choice"],
  ["TableCellRepeat#1.kind", "same fact, other arms"],
  ["TableCellRepeat#1.colspan", "span calculation input"],
  ["TableCellRepeat#1.rowspan", "rowVisits reservation"],
  ["TableCellRepeat#2.kind", "same fact, other arms"],
  ["TableCellRepeat#2.count", "span calculation input"],
]);

/**
 * Fields that are NOT recorded facts, each with a reason (shared
 * constants above for the common buckets, a short bespoke string for
 * the rest).
 */
export const EXEMPT: ReadonlyMap<string, string> = new Map([
  ["Location.offset", POSITION],
  ["Location.line", POSITION],
  ["Location.column", POSITION],
  ["Node.type", TYPE_DISCRIMINANT],
  ["Node.position", POSITION],
  ["DocumentNode.type", TYPE_DISCRIMINANT],
  ["DocumentNode.children", STRUCTURAL],
  ["ParagraphNode.type", TYPE_DISCRIMINANT],
  ["ParagraphNode.children", STRUCTURAL],
  ["TextNode.type", TYPE_DISCRIMINANT],
  ["TextNode.value", CONTENT],
  ["BoldNode.type", TYPE_DISCRIMINANT],
  ["BoldNode.role", CONTENT],
  ["BoldNode.children", STRUCTURAL],
  ["ItalicNode.type", TYPE_DISCRIMINANT],
  ["ItalicNode.role", CONTENT],
  ["ItalicNode.children", STRUCTURAL],
  ["MonospaceNode.type", TYPE_DISCRIMINANT],
  ["MonospaceNode.role", CONTENT],
  ["MonospaceNode.children", STRUCTURAL],
  ["HighlightNode.type", TYPE_DISCRIMINANT],
  ["HighlightNode.role", CONTENT],
  ["HighlightNode.children", STRUCTURAL],
  ["CurvedQuoteNode.type", TYPE_DISCRIMINANT],
  ["CurvedQuoteNode.children", STRUCTURAL],
  ["SuperscriptNode.type", TYPE_DISCRIMINANT],
  ["SuperscriptNode.children", STRUCTURAL],
  ["SubscriptNode.type", TYPE_DISCRIMINANT],
  ["SubscriptNode.children", STRUCTURAL],
  ["CharacterReferenceNode.type", TYPE_DISCRIMINANT],
  ["CharacterReferenceNode.value", CONTENT],
  ["EscapedMarkNode.type", TYPE_DISCRIMINANT],
  ["EscapedMarkNode.value", CONTENT],
  ["AttributeReferenceNode.type", TYPE_DISCRIMINANT],
  ["AttributeReferenceNode.name", CONTENT],
  ["LinkNode.type", TYPE_DISCRIMINANT],
  ["LinkNode.form", "own doc: unread"],
  ["LinkNode.target", CONTENT],
  ["XrefNode.type", TYPE_DISCRIMINANT],
  ["XrefNode.form", 'fixed "shorthand"'],
  ["XrefNode.target", CONTENT],
  ["XrefNode.text", "ordinary optional content"],
  ["InlineAnchorNode.type", TYPE_DISCRIMINANT],
  ["InlineAnchorNode.id", CONTENT],
  ["InlineMacroNode.type", TYPE_DISCRIMINANT],
  ["InlineMacroNode.name", CONTENT],
  ["InlineMacroNode.target", CONTENT],
  ["InlineMacroNode.attrlist", CONTENT],
  ["HardLineBreakNode.type", TYPE_DISCRIMINANT],
  ["RawLineNode.type", TYPE_DISCRIMINANT],
  ["RawLineNode.value", CONTENT],
  ["PassthroughNode.type", TYPE_DISCRIMINANT],
  ["PassthroughNode.value", CONTENT],
  ["HeadingNode.type", TYPE_DISCRIMINANT],
  ["HeadingNode.title", CONTENT],
  ["AuthorLineNode.type", TYPE_DISCRIMINANT],
  ["AuthorLineNode.value", CONTENT],
  ["RevisionLineNode.type", TYPE_DISCRIMINANT],
  ["RevisionLineNode.value", CONTENT],
  ["DocumentHeaderNode.type", TYPE_DISCRIMINANT],
  ["DocumentHeaderNode.title", CONTENT],
  ["DocumentHeaderNode.lines", STRUCTURAL],
  ["DiscreteHeadingNode.type", TYPE_DISCRIMINANT],
  ["DiscreteHeadingNode.title", CONTENT],
  ["CommentNode.type", TYPE_DISCRIMINANT],
  ["CommentNode.value", CONTENT],
  ["AttributeEntryNode.type", TYPE_DISCRIMINANT],
  ["AttributeEntryNode.name", CONTENT],
  ["AttributeEntryNode.value", CONTENT],
  ["ListNode.type", TYPE_DISCRIMINANT],
  ["ListNode.children", STRUCTURAL],
  ["LeafDelimitedBlockNode.type", TYPE_DISCRIMINANT],
  ["LeafDelimitedBlockNode.content", CONTENT],
  ["FencedCodeBlockNode.type", TYPE_DISCRIMINANT],
  ["FencedCodeBlockNode.content", CONTENT],
  ["MasqueradedBlockNode.type", TYPE_DISCRIMINANT],
  ["MasqueradedBlockNode.content", CONTENT],
  ["IndentedLiteralBlockNode.type", TYPE_DISCRIMINANT],
  ["IndentedLiteralBlockNode.content", CONTENT],
  ["ParagraphFormBlockNode.type", TYPE_DISCRIMINANT],
  ["ParagraphFormBlockNode.content", CONTENT],
  ["LeafDelimitedBlockNode.sourceDelimiter", SENTINEL],
  ["LeafDelimitedBlockNode.fenced", SENTINEL],
  ["LeafDelimitedBlockNode.language", SENTINEL],
  ["FencedCodeBlockNode.sourceDelimiter", SENTINEL],
  ["FencedCodeBlockNode.fenced", "fixed literal true"],
  ["MasqueradedBlockNode.fenced", SENTINEL],
  ["MasqueradedBlockNode.language", SENTINEL],
  ["IndentedLiteralBlockNode.sourceDelimiter", SENTINEL],
  ["IndentedLiteralBlockNode.fenced", SENTINEL],
  ["IndentedLiteralBlockNode.language", SENTINEL],
  ["ParagraphFormBlockNode.sourceDelimiter", SENTINEL],
  ["ParagraphFormBlockNode.fenced", SENTINEL],
  ["ParagraphFormBlockNode.language", SENTINEL],
  ["OpenParentBlockNode.type", TYPE_DISCRIMINANT],
  ["OpenParentBlockNode.variant", 'fixed "open"'],
  ["OpenParentBlockNode.children", STRUCTURAL],
  ["CompoundParentBlockNode.type", TYPE_DISCRIMINANT],
  ["CompoundParentBlockNode.openDelimiter", SENTINEL],
  ["CompoundParentBlockNode.children", STRUCTURAL],
  ["AdmonitionNode.type", TYPE_DISCRIMINANT],
  ["AdmonitionNode.variant", "label text, case only"],
  ["AdmonitionNode.text", STRUCTURAL],
  ["AdmonitionNode.children", STRUCTURAL],
  ["ThematicBreakNode.type", TYPE_DISCRIMINANT],
  ["BlockMacroNode.type", TYPE_DISCRIMINANT],
  ["BlockMacroNode.name", CONTENT],
  ["BlockMacroNode.target", CONTENT],
  ["BlockMacroNode.attrlist", CONTENT],
  ["FrontMatterNode.type", TYPE_DISCRIMINANT],
  ["FrontMatterNode.content", CONTENT],
  ["PreprocessorDirectiveNode.type", TYPE_DISCRIMINANT],
  ["PreprocessorDirectiveNode.value", CONTENT],
  ["PageBreakNode.type", TYPE_DISCRIMINANT],
  ["ItemBody.text", STRUCTURAL],
  ["ItemBody.blocks", STRUCTURAL],
  ["ListItemNode.type", TYPE_DISCRIMINANT],
  ["ItemBlock.block", STRUCTURAL],
  ["DescriptionListNode.type", TYPE_DISCRIMINANT],
  ["DescriptionListNode.delimiter", "grouping key, not bytes"],
  ["DescriptionListNode.children", STRUCTURAL],
  ["DescriptionTermNode.type", TYPE_DISCRIMINANT],
  ["DescriptionTermNode.children", STRUCTURAL],
  ["DescriptionListItemNode.type", TYPE_DISCRIMINANT],
  ["DescriptionListItemNode.terms", STRUCTURAL],
  ["DescriptionListItemNode.textLines", "replay bytes; printing is the fact"],
  ["TermEntry.term", STRUCTURAL],
  ["TermGapComment.comment", CONTENT],
  ["BlockAttributeListNode.type", TYPE_DISCRIMINANT],
  ["BlockAttributeListNode.value", CONTENT],
  ["BlockTitleNode.type", TYPE_DISCRIMINANT],
  ["BlockTitleNode.title", CONTENT],
  ["BlockAnchorNode.type", TYPE_DISCRIMINANT],
  ["BlockAnchorNode.id", CONTENT],
  ["BlockAnchorNode.reftext", "ordinary optional content"],
  ["TableNode.type", TYPE_DISCRIMINANT],
  ["TableNode.children", STRUCTURAL],
  ["TableNode.close", CONTAINER],
  ["TableNode.cutting", CONTAINER],
  ["TableNode.header", "own doc: derived predicate"],
  ["TableNode.footer", UNREAD],
  ["TableClose#0.image", UNREAD],
  ["TableColumnSpec.halign", UNREAD],
  ["TableColumnSpec.valign", UNREAD],
  ["TableRowNode.type", TYPE_DISCRIMINANT],
  ["TableRowNode.children", STRUCTURAL],
  ["TableCellNode.type", TYPE_DISCRIMINANT],
  ["TableCellNode.opening", CONTAINER],
  ["TableCellNode.runs", CONTAINER],
  ["TableCellNode.repeat", CONTAINER],
  ["TableCellOpening#0.parsed", CONTAINER],
  ["TableCellOpening#0.spec", "concatenated unconditionally into cellImage"],
  [
    "TableCellOpening#0.separator",
    "concatenated unconditionally into cellImage",
  ],
  ["TableCellOpening#0.offset", POSITION],
  ["TableCellOpening#1.offset", POSITION],
  ["TableTextRun.offset", POSITION],
  ["TableCellSpec.repeat", UNREAD],
  ["TableCellSpec.halign", UNREAD],
  ["TableCellSpec.valign", UNREAD],
]);
