/**
 * The shared ledger writer's claim (issue #271): what it puts on disk
 * is already in Prettier-normal form, so `bun run fmt:check` holds
 * over a tree a `--write` has just touched.
 *
 * The planted tree is the whole point, and it carries the two shapes
 * that decide the question. A SHORT ARRAY is the shape the two
 * spellings disagree about: `JSON.stringify(value, undefined, 2)`
 * breaks an array over as many lines as it has elements and Prettier
 * keeps a short one on a single line, so a hand-rolled writer's output
 * stays Prettier-normal only while no such array appears in it. A
 * SHORT OBJECT is the shape that decides the writer's own spelling:
 * Prettier preserves the break an object already has after its `{`, so
 * the indented serialization the writer hands it keeps one key per
 * line where a compact one would collapse the object.
 *
 * Asserting against Prettier's own `check` rather than against a
 * pinned string means the first claim does not have to be rewritten
 * when Prettier's JSON spelling changes.
 *
 * The scratch directory is throwaway OUTPUT, not a committed input:
 * the thing under test is a writer, so there is nothing to check in.
 */
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { check } from "prettier";
import { afterAll, describe, expect, test } from "vitest";
import { writeLedgerFile } from "../../scripts/lib/ledger-file.js";

const scratch = mkdtempSync(path.join(tmpdir(), "ledger-file-"));

afterAll(() => {
  rmSync(scratch, { recursive: true, force: true });
});

/**
 * A ledger shaped like the ones the harnesses write: a note, rows
 * keyed by id, and short arrays and objects short enough that Prettier
 * would fit either on one line.
 */
const PLANTED = {
  note: "Generated by a test.",
  rows: {
    "one/fence0": { family: "X", examples: ["l0c6", "l1c7"] },
    "two/indent0": { family: "X", examples: ["l0c37"] },
    "three/empty": { family: "X", examples: [] },
  },
};

/** What a hand-rolled writer would have put on disk for {@link PLANTED}. */
const HAND_ROLLED = `${JSON.stringify(PLANTED, undefined, 2)}\n`;

/**
 * Writes the planted tree to its own file under the scratch directory.
 * @param name - the file to write, unique per test
 * @returns the bytes that reached disk
 */
async function written(name: string): Promise<string> {
  const file = path.join(scratch, name);
  await writeLedgerFile(file, PLANTED);
  return readFileSync(file, "utf8");
}

describe("writeLedgerFile", () => {
  test("writes a file Prettier already considers formatted", async () => {
    await expect(
      check(await written("planted.json"), { parser: "json" }),
    ).resolves.toBe(true);
  });

  // Red before the writer existed: the hand-rolled spelling every
  // `--write` path used is NOT what Prettier would have written, which
  // is the whole of issue #271.
  test("a hand-rolled writer would not have been formatted", async () => {
    await expect(check(HAND_ROLLED, { parser: "json" })).resolves.toBe(false);
    expect(await written("planted-hand-rolled.json")).not.toBe(HAND_ROLLED);
  });

  test("collapses a short array, which is where the two differ", async () => {
    expect(await written("planted-arrays.json")).toContain(
      '"examples": ["l0c6", "l1c7"]',
    );
  });

  test("keeps one key per line, the shape the tree already carries", async () => {
    expect(await written("planted-objects.json")).toContain(
      '\n    "two/indent0": {\n      "family": "X",',
    );
  });

  test("round-trips the tree it was handed", async () => {
    expect(JSON.parse(await written("planted-roundtrip.json"))).toEqual(
      PLANTED,
    );
  });
});
